### ISSUE TITLE
MD5? Consider SHA256

### ISSUE THREAD

**Issue by pmorton** [d3zd3z/gosure#10]
Hi - While doing a quick review after seeing the project on reddit, I found myself cringing at the use of MD5. While I understand that your indented use case is not specifically security related, using MD5 specifically excludes any security related use cases. Please consider a secure cipher like sha256.

**Comment by d3zd3z** [comment]
Gosure doesn't use md5, it is just an example in the README of an old way of doing file integrity. All hashes are currently sha1. I may want to move to sha256 at some point, although I'd have to think about what to do about compatibility with existing surefiles.

**Comment by d3zd3z** [comment]
Closing issue. I'll create another issue to track the possibility of moving from SHA1 to SHA256.
